version: 2
references:
  tagfilter: &tagfilter
    filters:
      tags:
        only: /.*/
  storepackages: &storepackages
    store_artifacts:
      path: packages
  buildrpmpackage: &buildrpmpackage
    run:
      command: |
        [[ "$CIRCLE_TAG" ]] && VERSION="$CIRCLE_TAG" || VERSION="${CIRCLE_BRANCH}_${CIRCLE_BUILD_NUM}"
        mkdir -p packages
        fpm --rpm-autoreqprov --rpm-dist $CIRCLE_JOB -t rpm -n heictojpeg -v $VERSION -p packages -s dir Bins/heiftojpeg=/usr/bin/
  cmake: &cmake
    run:
      command: cmake ..
      working_directory: build
  make: &make
    run:
      command: make
      working_directory: build
  packagefiles: &packagefiles
    persist_to_workspace:
      root: $CIRCLE_WORKING_DIRECTORY
      paths:
        - packages/*
jobs:
  el6:
    docker:
      - image: andyshinn/heif:el6
    steps:
      - checkout
      - *cmake
      - *make
      - *buildrpmpackage
      - *storepackages
  el7:
    docker:
      - image: andyshinn/heif:el7
    steps:
      - checkout
      - *cmake
      - *make
      - *buildrpmpackage
      - *storepackages
  deploy:
    docker:
      - image: andyshinn/heif:el7
    steps:
      - attach_workspace:
          at: /tmp/packages
      - deploy:
          command: |
            [[ "$CIRCLE_TAG" ]] && VERSION="$CIRCLE_TAG" || VERSION="${CIRCLE_BRANCH}_${CIRCLE_BUILD_NUM}"
            package_cloud push keenai/heiftojpeg/el/7 /tmp/packages/heictojpeg-$VERSION-1.el7.x86_64.rpm
            package_cloud push keenai/heiftojpeg/el/6 /tmp/packages/heictojpeg-$VERSION-1.el6.x86_64.rpm
workflows:
  version: 2
  build:
    jobs:
      - el6:
          <<: *tagfilter
      - el7:
          <<: *tagfilter
      - deploy:
          <<: *tagfilter
          requires:
            - el6
            - el7
          filters:
            branches:
              ignore: /.*/
deployment:
  trigger_tag:
    tag: /.*/
